---
# yamllint disable rule:comments rule:line-length
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_call:
env:
  JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  MAVEN_ARGS: "-B -V -ntp"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: maven
          server-id: ossrh
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Build and Deploy
        run: ./mvnw -Prelease deploy
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
