---
# yamllint disable rule:comments rule:line-length
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      java-version:
        description: 'The Java version that is going to be set up.'
        default: '17'
        required: false
        type: string
      java-distribution:
        description: 'The Java distribution that is going to be set up.'
        default: 'zulu'
        required: false
        type: string
      maven-server-id:
        description: 'The server-id used for authentication.'
        default: 'ossrh'
        required: false
        type: string
env:
  JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  MAVEN_ARGS: "-B -V -ntp"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: maven
          server-id: ${{ inputs.maven-server-id }}
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Build and Deploy
        run: ./mvnw -B -V -ntp -Prelease deploy
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
