---
# yamllint disable rule:comments rule:line-length
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      java-version:
        description: 'The Java version that is going to be set up.'
        default: '17'
        required: false
        type: string
      java-distribution:
        description: 'The Java distribution that is going to be set up.'
        default: 'zulu'
        required: false
        type: string
      maven-server-id:
        description: 'The server-id used for authentication.'
        default: 'ossrh'
        required: false
        type: string
env:
  JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  MAVEN_ARGS: "-B -V -ntp"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: maven
          server-id: ${{ inputs.maven-server-id }}
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: Build and Deploy
        run: ./mvnw -B -V -ntp -Dgpg.signer=bc -Prelease deploy
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
