---
# yamllint disable rule:comments rule:line-length
name: yamllint
# yamllint disable-line rule:truthy
on:
  workflow_call:
jobs:
  yamllint:
    name: "\U0001F9F9 yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 🧹 Run yamllint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
