---
# yamllint disable rule:comments rule:line-length
name: yamllint
# yamllint disable-line rule:truthy
on:
  workflow_call:
jobs:
  yamllint:
    name: "\U0001F9F9 yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: 🧹 Run yamllint
        uses: frenck/action-yamllint@34b4bbcaeabedcfefad6adea8c5bbc42af0e2d47 # v1.5.0
