---
# yamllint disable rule:comments rule:line-length
name: yamllint
# yamllint disable-line rule:truthy
on:
  workflow_call:
jobs:
  yamllint:
    name: "\U0001F9F9 yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: 🧹 Run yamllint
        uses: frenck/action-yamllint@34b4bbcaeabedcfefad6adea8c5bbc42af0e2d47 # v1.5.0
