---
# yamllint disable rule:comments rule:line-length
name: yamllint
# yamllint disable-line rule:truthy
on:
  workflow_call:
jobs:
  yamllint:
    name: "\U0001F9F9 yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 🧹 Run yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          yamllint_flags: |
            --config-data "{rules: {line-length: {max: 120}}}" .
